force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Hiring__c.field-meta.xml
<CustomField>
    <fullName>Hiring__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring</label>
    <referenceTo>Hiring__c</referenceTo>
    <relationshipLabel>Hiring List</relationshipLabel>
    <relationshipName>Hiring</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Screening</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Selected</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hiring__c/Hiring__c.object-meta.xml
<CustomObject>
    <label>Hiring</label>
    <nameField>
        <displayFormat>H-{0}</displayFormat>
        <label>Hiring Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hirings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CandidateTriggerHandler.cls
public with sharing class CandidateTriggerHandler {
	
	public static void setScoreOnStatusUpdate(List<Candidate__c> canNewList) {
		if(!canNewList.isEmpty()) {
			for(Candidate__c canNew: canNewList) {
				if(canNew.Status__c == 'Selected') {
					canNew.Score__c = 10;
				} else if(canNew.Status__c == 'Rejected') {
					canNew.Score__c = -5;
				} else {
					canNew.Score__C = 0;
				}
			} 
		}	
	}
	
    public static void setTotalScoreOnStatusUpdate(Map<Id, Candidate__c> canNewMap, Map<Id, Candidate__c> canOldMap) {
        Set<Id> hiringIdsSet = new Set<Id>();
        if(!canNewMap.isEmpty()) {
            for(Candidate__c canNew: canNewMap.values()) {
                if(canNew.Status__c != canOldMap.get(canNew.id).Status__c && canNew.Hiring__c != null) {
                    hiringIdsSet.add(canNew.Hiring__c);
                }
                
            } 
        }
		updateHiringRecords(hiringIdsSet);
    }
	
	public static void updateHiringRecords(Set<Id> hiringIdsSet) {
		if(hiringIdsSet.isEmpty()) {
			return;
		}
		List<Hiring__c> updateHrList = new List<Hiring__c>();
		List<AggregateResult> agResultList = [SELECT Sum(Score__c) totalScore, AVG(Score__c) avgScore, Hiring__c  
						FROM Candidate__c WHERE Hiring__c =: hiringIdsSet AND Status__c IN ('Selected', 'Rejected') WITH USER_MODE Group By Hiring__c LIMIT 10000 ];
		
		if(!agResultList.isEmpty()) {
			for(AggregateResult ag: agResultList) {
				Hiring__c hr = new Hiring__c();
				hr.Id = (Id)ag.get('Hiring__c');
				hr.Total_Score__c = (Decimal)ag.get('totalScore');
				hr.Average_Score__c = (Decimal)ag.get('avgScore');
				updateHrList.add(hr);
			}
		}
		
		if(!updateHrList.isEmpty()) {
            try {
                if(Schema.SObjectType.Hiring__c.isUpdateable()) {
                    Database.update (updateHrList, AccessLevel.USER_MODE);
                }
            } catch (Exception e) {
                throw new AuraHandledException(e.getMessage());
            }
            
		}
	}
}